### ISSUE TITLE
请问cv岗中对C++的基础概念看重吗？

### ISSUE THREAD

**Issue by zhoulukuan** [amusi/AI-Job-Notes#1]
您好，因为个人感觉刷题的时候，对常见的堆栈、队列、哈希表这些更侧重应用。对一些基础或者更高级的概念，比如关键字、数据结构空间占用与地址开销甚至一些编译过程与原理，个人是比较薄弱的，有必要专门去复习吗？

**Comment by amusi** [comment]
C++是一个加分项，事实上有一些搞CV，特别偏向深度学习方向的人，他们对C++并不熟悉，所以做项目或者刷题都是用Python。所以说C++是加分项，很大的加分项，有些大公司挺爱考这方面知识的，比如腾讯。
