### ISSUE TITLE
有没有AI方面的刷题指南

### ISSUE THREAD

**Issue by XcodeHw** [amusi/AI-Job-Notes#2]
我想问一下，哪些地方可以刷ai的题(数学题和面试经常问的题)比如深度学习，传统机器学习，计算机视觉等方面的，编程题我知道有Leetcode ,还有剑指offer

**Comment by amusi** [comment]
你好，2019年3月底/4月初会更新深度学习题库（含机器学习、深度学习、计算机视觉、传统图像处理等资料），敬请期待！

**Comment by amusi** [comment]
> 我想问一下，哪些地方可以刷ai的题(数学题和面试经常问的题)比如深度学习，传统机器学习，计算机视觉等方面的，编程题我知道有Leetcode ,还有剑指offer
