### ISSUE TITLE
强化学习的求职情况及前景如何？

### ISSUE THREAD

**Issue by LyWangPX** [amusi/AI-Job-Notes#3]
数学本科毕业(UCLA), 目前在日本就读另一个本科（设计系），在日本小公司做视觉识别实习（Resnet），自己喜欢研究强化学习（参见我自己的github小项目）。不知道该怎么准备求职。该怎么定位？

**Comment by amusi** [comment]
对国内来说：刷题+背题+项目+实习+竞赛+顶会/顶刊(可选)
