### ISSUE TITLE
为什么刷算法不建议使用java？

### ISSUE THREAD

**Issue by JerryQiang** [amusi/AI-Job-Notes#4]
是因为日常使用python，然后将C++作为加分项吗？
还是因为别的什么原因呢？

**Comment by amusi** [comment]
对于算法工程师来说，Python是必选项，C++是加分项。JAVA呢？这里并不觉得是优势，所以为什么要用JAVA刷题呢

**Comment by JerryQiang** [comment]
但是java.util提供的数据类型比较齐全（尤其是jdk1.8），而python的数据结构太抽象，反而不好用
其次我在牛客网用python写标准解法过了几道oj超时了，用java就过了，C++肯定过
我想再进一步提问：
关于C++作为加分项，Python向Cthon进阶？C++要去学STL吗？

**Comment by JerryQiang** [comment]
我本科有编程基础，c++，java都有掌握，但我觉得只论刷算法而言，我现在学习java刷算法题更节省时间成本。

**Comment by xwr96** [comment]
@JerryQiang Java开发好找工作

**Comment by JerryQiang** [comment]
> @JerryQiang Java开发好找工作

我现在就在秋招，找java开发工作

**Comment by xwr96** [comment]
> > @JerryQiang Java开发好找工作
> 
> 我现在就在秋招，找java开发工作

兄弟找的咋样？

**Comment by JerryQiang** [comment]
> > > @JerryQiang Java开发好找工作
> > 
> > 
> > 我现在就在秋招，找java开发工作
> 
> 兄弟找的咋样？

9月初才投，一直在笔试，没有收到面试邀约，欲哭无泪

**Comment by xwr96** [comment]
@JerryQiang 今年疫情所以可能有点难。我一个师兄也是一直笔试还没参加过面试

**Comment by JerryQiang** [comment]
> @JerryQiang 今年疫情所以可能有点难。我一个师兄也是一直笔试还没参加过面试

自己也有原因，在准备面试复习，没投提前批，你后面找工作早点投简历吧，
另外能出去实习就去实习，我暑假去实习的同学都有转正offer
有保底，心不慌，这样会好很多

**Comment by xwr96** [comment]
> > @JerryQiang 今年疫情所以可能有点难。我一个师兄也是一直笔试还没参加过面试
> 
> 自己也有原因，在准备面试复习，没投提前批，你后面找工作早点投简历吧，
> 另外能出去实习就去实习，我暑假去实习的同学都有转正offer
> 有保底，心不慌，这样会好很多

嗯嗯，好的，谢谢啦
