### ISSUE TITLE
AI方面需要如何准备呢

### ISSUE THREAD

**Issue by houkensjtu** [amusi/AI-Job-Notes#5]
RT，这里的准备内容只提到算法数据结构，感觉和普通程序员的招聘一样，实际企业在招聘AI机械学习的岗位时，是只考察这些内容吗？ 或者说AI方面完全由在校期间的科研成果决定，准备了也没有用的意思吗？

**Comment by amusi** [comment]
0. 很棒的问题，其实我是还没有这部分内容加进去，你可以看一下另一个库【深度学习面试宝典】，这个应该是你想要的：https://github.com/amusi/Deep-Learning-Interview-Book

**Comment by houkensjtu** [comment]
@amusi 谢谢链接！稍微岔开一下话题，我看楼主从前也做过很系统的算法与数据结构准备，想必也考虑过面试软件工程师。能谈谈你对软件工程师和AI工程师这两个职业的看法吗？（诸如各有什么利弊，特别是对于还没有入行的人来说）谢谢啦！

**Comment by amusi** [comment]
其实你说错了，我只找过AI算法工程师（CV方向），不过身边有很多朋友去做软开了。算法与数据结构是程序员的基础，不管你前端也好，后端也好，或者AI方向也好，都需要学习这个算法与数据结构的。至于利弊，欢迎到求职星球里来讨论：https://t.zsxq.com/VFUZR3n
